//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FinishBattleRequest.proto
// Note: requires additional types generated from: ApiRequest.proto
// Note: requires additional types generated from: UnitGroup.proto
namespace SlgPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FinishBattleRequest")]
  public partial class FinishBattleRequest : global::ProtoBuf.IExtensible
  {
    public FinishBattleRequest() {}
    
    private ApiRequest _api = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"api", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ApiRequest api
    {
      get { return _api; }
      set { _api = value; }
    }
    private int _fightId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fightId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightId
    {
      get { return _fightId; }
      set { _fightId = value; }
    }
    private readonly global::System.Collections.Generic.List<UnitGroup> _unitGroup = new global::System.Collections.Generic.List<UnitGroup>();
    [global::ProtoBuf.ProtoMember(3, Name=@"unitGroup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UnitGroup> unitGroup
    {
      get { return _unitGroup; }
    }
  
    private int _fightResult = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"fightResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightResult
    {
      get { return _fightResult; }
      set { _fightResult = value; }
    }
    private int _star = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int star
    {
      get { return _star; }
      set { _star = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}