//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LoginResponse.proto
// Note: requires additional types generated from: ApiResponse.proto
// Note: requires additional types generated from: Unit.proto
// Note: requires additional types generated from: UnitGroup.proto
// Note: requires additional types generated from: Mission.proto
// Note: requires additional types generated from: Item.proto
// Note: requires additional types generated from: Hero.proto
namespace SlgPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResponse")]
  public partial class LoginResponse : global::ProtoBuf.IExtensible
  {
    public LoginResponse() {}
    
    private ApiResponse _response = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ApiResponse response
    {
      get { return _response; }
      set { _response = value; }
    }
    private string _ticket = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ticket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ticket
    {
      get { return _ticket; }
      set { _ticket = value; }
    }
    private readonly global::System.Collections.Generic.List<Unit> _units = new global::System.Collections.Generic.List<Unit>();
    [global::ProtoBuf.ProtoMember(3, Name=@"units", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Unit> units
    {
      get { return _units; }
    }
  
    private readonly global::System.Collections.Generic.List<UnitGroup> _unitGroups = new global::System.Collections.Generic.List<UnitGroup>();
    [global::ProtoBuf.ProtoMember(4, Name=@"unitGroups", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UnitGroup> unitGroups
    {
      get { return _unitGroups; }
    }
  
    private int _repairEndTime = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"repairEndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int repairEndTime
    {
      get { return _repairEndTime; }
      set { _repairEndTime = value; }
    }
    private int _repairTotalTime = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"repairTotalTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int repairTotalTime
    {
      get { return _repairTotalTime; }
      set { _repairTotalTime = value; }
    }
    private readonly global::System.Collections.Generic.List<Mission> _missons = new global::System.Collections.Generic.List<Mission>();
    [global::ProtoBuf.ProtoMember(7, Name=@"missons", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Mission> missons
    {
      get { return _missons; }
    }
  
    private readonly global::System.Collections.Generic.List<Item> _items = new global::System.Collections.Generic.List<Item>();
    [global::ProtoBuf.ProtoMember(8, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Item> items
    {
      get { return _items; }
    }
  
    private readonly global::System.Collections.Generic.List<Hero> _heroes = new global::System.Collections.Generic.List<Hero>();
    [global::ProtoBuf.ProtoMember(9, Name=@"heroes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Hero> heroes
    {
      get { return _heroes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}