//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RepairUnitResponse.proto
// Note: requires additional types generated from: ApiResponse.proto
// Note: requires additional types generated from: Unit.proto
namespace SlgPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RepairUnitResponse")]
  public partial class RepairUnitResponse : global::ProtoBuf.IExtensible
  {
    public RepairUnitResponse() {}
    
    private ApiResponse _response = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ApiResponse response
    {
      get { return _response; }
      set { _response = value; }
    }
    private readonly global::System.Collections.Generic.List<Unit> _units = new global::System.Collections.Generic.List<Unit>();
    [global::ProtoBuf.ProtoMember(2, Name=@"units", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Unit> units
    {
      get { return _units; }
    }
  
    private int _repairEndTime = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"repairEndTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int repairEndTime
    {
      get { return _repairEndTime; }
      set { _repairEndTime = value; }
    }
    private int _repairTotalTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"repairTotalTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int repairTotalTime
    {
      get { return _repairTotalTime; }
      set { _repairTotalTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}