//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GetPVPLogResponse.proto
// Note: requires additional types generated from: ApiResponse.proto
// Note: requires additional types generated from: FightLog.proto
namespace SlgPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetPVPLogResponse")]
  public partial class GetPVPLogResponse : global::ProtoBuf.IExtensible
  {
    public GetPVPLogResponse() {}
    
    private ApiResponse _response = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ApiResponse response
    {
      get { return _response; }
      set { _response = value; }
    }
    private readonly global::System.Collections.Generic.List<FightLog> _fightLogs = new global::System.Collections.Generic.List<FightLog>();
    [global::ProtoBuf.ProtoMember(2, Name=@"fightLogs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FightLog> fightLogs
    {
      get { return _fightLogs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}