//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: InitResponse.proto
// Note: requires additional types generated from: ApiResponse.proto
// Note: requires additional types generated from: FileDesc.proto
namespace SlgPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitResponse")]
  public partial class InitResponse : global::ProtoBuf.IExtensible
  {
    public InitResponse() {}
    
    private ApiResponse _response = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"response", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ApiResponse response
    {
      get { return _response; }
      set { _response = value; }
    }
    private string _configUrl = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"configUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string configUrl
    {
      get { return _configUrl; }
      set { _configUrl = value; }
    }
    private readonly global::System.Collections.Generic.List<FileDesc> _fileDesc = new global::System.Collections.Generic.List<FileDesc>();
    [global::ProtoBuf.ProtoMember(3, Name=@"fileDesc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<FileDesc> fileDesc
    {
      get { return _fileDesc; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}