//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UpgradeBuildingRequest.proto
// Note: requires additional types generated from: ApiRequest.proto
namespace SlgPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpgradeBuildingRequest")]
  public partial class UpgradeBuildingRequest : global::ProtoBuf.IExtensible
  {
    public UpgradeBuildingRequest() {}
    
    private ApiRequest _api = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"api", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public ApiRequest api
    {
      get { return _api; }
      set { _api = value; }
    }
    private int _buildingId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buildingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buildingId
    {
      get { return _buildingId; }
      set { _buildingId = value; }
    }
    private int _byCash = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"byCash", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int byCash
    {
      get { return _byCash; }
      set { _byCash = value; }
    }
    private int _buyQueue = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buyQueue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyQueue
    {
      get { return _buyQueue; }
      set { _buyQueue = value; }
    }
    private int _buyCd = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"buyCd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buyCd
    {
      get { return _buyCd; }
      set { _buyCd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}