//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ApiRequest.proto
namespace SlgPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApiRequest")]
  public partial class ApiRequest : global::ProtoBuf.IExtensible
  {
    public ApiRequest() {}
    
    private string _v = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"v", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string v
    {
      get { return _v; }
      set { _v = value; }
    }
    private string _callId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"callId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string callId
    {
      get { return _callId; }
      set { _callId = value; }
    }
    private string _sign = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sign", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sign
    {
      get { return _sign; }
      set { _sign = value; }
    }
    private string _ticket = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ticket", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ticket
    {
      get { return _ticket; }
      set { _ticket = value; }
    }
    private int _s = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"s", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int s
    {
      get { return _s; }
      set { _s = value; }
    }
    private int _snid = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"snid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int snid
    {
      get { return _snid; }
      set { _snid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}