//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MultiPrizeItem.proto
// Note: requires additional types generated from: PrizeItem.proto
namespace SlgPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MultiPrizeItem")]
  public partial class MultiPrizeItem : global::ProtoBuf.IExtensible
  {
    public MultiPrizeItem() {}
    
    private readonly global::System.Collections.Generic.List<PrizeItem> _prizeItems = new global::System.Collections.Generic.List<PrizeItem>();
    [global::ProtoBuf.ProtoMember(1, Name=@"prizeItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PrizeItem> prizeItems
    {
      get { return _prizeItems; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}