//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PVPUser.proto
// Note: requires additional types generated from: UnitGroup.proto
// Note: requires additional types generated from: Unit.proto
// Note: requires additional types generated from: Hero.proto
namespace SlgPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVPUser")]
  public partial class PVPUser : global::ProtoBuf.IExtensible
  {
    public PVPUser() {}
    
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private int _headPicId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headPicId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headPicId
    {
      get { return _headPicId; }
      set { _headPicId = value; }
    }
    private int _honor = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"honor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int honor
    {
      get { return _honor; }
      set { _honor = value; }
    }
    private int _rank = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private int _fightPower = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fightPower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightPower
    {
      get { return _fightPower; }
      set { _fightPower = value; }
    }
    private readonly global::System.Collections.Generic.List<UnitGroup> _unitGroups = new global::System.Collections.Generic.List<UnitGroup>();
    [global::ProtoBuf.ProtoMember(7, Name=@"unitGroups", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<UnitGroup> unitGroups
    {
      get { return _unitGroups; }
    }
  
    private readonly global::System.Collections.Generic.List<Unit> _units = new global::System.Collections.Generic.List<Unit>();
    [global::ProtoBuf.ProtoMember(8, Name=@"units", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Unit> units
    {
      get { return _units; }
    }
  
    private readonly global::System.Collections.Generic.List<Hero> _heroes = new global::System.Collections.Generic.List<Hero>();
    [global::ProtoBuf.ProtoMember(9, Name=@"heroes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Hero> heroes
    {
      get { return _heroes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}