//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ShopItem.proto
namespace SlgPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShopItem")]
  public partial class ShopItem : global::ProtoBuf.IExtensible
  {
    public ShopItem() {}
    
    private int _posId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"posId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int posId
    {
      get { return _posId; }
      set { _posId = value; }
    }
    private int _itemType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    private int _itemID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"itemID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemID
    {
      get { return _itemID; }
      set { _itemID = value; }
    }
    private int _num = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private int _priceType = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"priceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int priceType
    {
      get { return _priceType; }
      set { _priceType = value; }
    }
    private int _price = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private int _isSold = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isSold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isSold
    {
      get { return _isSold; }
      set { _isSold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}